# Generated by Django 5.2 on 2025-04-11 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0002_release_release_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='release',
            name='release_date',
        ),
    ]
